{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red28\green71\blue110;\red255\green255\blue255;\red26\green26\blue26;
\red7\green64\blue153;\red98\green0\blue117;\red135\green136\blue100;}
{\*\expandedcolortbl;;\cssrgb\c13725\c35294\c50588;\cssrgb\c100000\c100000\c100000;\cssrgb\c13333\c13333\c13333;
\cssrgb\c0\c33333\c66667;\cssrgb\c46667\c0\c53333;\cssrgb\c60000\c60000\c46667;}
\paperw11900\paperh16840\margl1440\margr1440\vieww24780\viewh11960\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt 
\f0\fs21\fsmilli10660 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 ALTER}}
\f0\fs21\fsmilli10660 \cf4 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura_linea`\cf4 \strokec4 \'a0\cf6 \strokec6 DROP\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_DAC3517AF04F795F`\cf4 \strokec4 ;\'a0\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura_linea`\cf4 \strokec4 \'a0\cf6 \strokec6 ADD\cf4 \strokec4 \'a0\cf6 \strokec6 CONSTRAINT\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_DAC3517AF04F795F`\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf7 \strokec7 (\cf5 \strokec5 `factura_id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 REFERENCES\cf4 \strokec4 \'a0\cf5 \strokec5 `factura`\cf7 \strokec7 (\cf5 \strokec5 `id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/delete.html"}}{\fldrslt \cf2 \strokec2 DELETE}}\'a0\cf6 \strokec6 CASCADE\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/update.html"}}{\fldrslt \cf2 \strokec2 UPDATE}}\'a0\cf6 \strokec6 RESTRICT\cf4 \strokec4 ;\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura`\cf4 \strokec4 \'a0\cf6 \strokec6 DROP\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_F9EBA00944168F7D`\cf4 \strokec4 ;\'a0\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura`\cf4 \strokec4 \'a0\cf6 \strokec6 ADD\cf4 \strokec4 \'a0\cf6 \strokec6 CONSTRAINT\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_F9EBA00944168F7D`\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf7 \strokec7 (\cf5 \strokec5 `tratamiento_id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 REFERENCES\cf4 \strokec4 \'a0\cf5 \strokec5 `tratamiento`\cf7 \strokec7 (\cf5 \strokec5 `id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/delete.html"}}{\fldrslt \cf2 \strokec2 DELETE}}\'a0\cf6 \strokec6 CASCADE\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/update.html"}}{\fldrslt \cf2 \strokec2 UPDATE}}\'a0\cf6 \strokec6 RESTRICT\cf4 \strokec4 ;\'a0\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura`\cf4 \strokec4 \'a0\cf6 \strokec6 DROP\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_F9EBA009DE734E51`\cf4 \strokec4 ;\'a0\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `factura`\cf4 \strokec4 \'a0\cf6 \strokec6 ADD\cf4 \strokec4 \'a0\cf6 \strokec6 CONSTRAINT\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_F9EBA009DE734E51`\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf7 \strokec7 (\cf5 \strokec5 `cliente_id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 REFERENCES\cf4 \strokec4 \'a0\cf5 \strokec5 `cliente`\cf7 \strokec7 (\cf5 \strokec5 `id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/delete.html"}}{\fldrslt \cf2 \strokec2 DELETE}}\'a0\cf6 \strokec6 CASCADE\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/update.html"}}{\fldrslt \cf2 \strokec2 UPDATE}}\'a0\cf6 \strokec6 RESTRICT\cf4 \strokec4 ;\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `tratamiento_concepto`\cf4 \strokec4 \'a0\cf6 \strokec6 DROP\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_86D5317F44168F7D`\cf4 \strokec4 ;\'a0\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `tratamiento_concepto`\cf4 \strokec4 \'a0\cf6 \strokec6 ADD\cf4 \strokec4 \'a0\cf6 \strokec6 CONSTRAINT\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_86D5317F44168F7D`\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf7 \strokec7 (\cf5 \strokec5 `tratamiento_id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 REFERENCES\cf4 \strokec4 \'a0\cf5 \strokec5 `tratamiento`\cf7 \strokec7 (\cf5 \strokec5 `id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/delete.html"}}{\fldrslt \cf2 \strokec2 DELETE}}\'a0\cf6 \strokec6 CASCADE\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/update.html"}}{\fldrslt \cf2 \strokec2 UPDATE}}\'a0\cf6 \strokec6 RESTRICT\cf4 \strokec4 ;\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `tratamiento`\cf4 \strokec4 \'a0\cf6 \strokec6 DROP\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_61A4A07CDE734E51`\cf4 \strokec4 ;\
{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 ALTER}}\'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/alter-table.html"}}{\fldrslt \cf2 \strokec2 TABLE}}\'a0\cf5 \strokec5 `tratamiento`\cf4 \strokec4 \'a0\cf6 \strokec6 ADD\cf4 \strokec4 \'a0\cf6 \strokec6 CONSTRAINT\cf4 \strokec4 \'a0\cf5 \strokec5 `FK_61A4A07CDE734E51`\cf4 \strokec4 \'a0\cf6 \strokec6 FOREIGN\cf4 \strokec4 \'a0\cf6 \strokec6 KEY\cf4 \strokec4 \'a0\cf7 \strokec7 (\cf5 \strokec5 `cliente_id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 REFERENCES\cf4 \strokec4 \'a0\cf5 \strokec5 `cliente`\cf7 \strokec7 (\cf5 \strokec5 `id`\cf7 \strokec7 )\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/delete.html"}}{\fldrslt \cf2 \strokec2 DELETE}}\'a0\cf6 \strokec6 CASCADE\cf4 \strokec4 \'a0\cf6 \strokec6 ON\cf4 \strokec4 \'a0{\field{\*\fldinst{HYPERLINK "http://localhost/phpmyadmin/url.php?url=https://dev.mysql.com/doc/refman/5.5/en/update.html"}}{\fldrslt \cf2 \strokec2 UPDATE}}\'a0\cf6 \strokec6 RESTRICT\cf4 \strokec4 ;}